server:
  ssl:
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}

spring:
  datasource:
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
    com.palmar: DEBUG

samba:
  host: ${SAMBA_HOST}
  share: ${SAMBA_SHARE}
  folder: ${SAMBA_FOLDER}
  domain: ${SAMBA_DOMAIN}

auth:
  datasource:
    url: ${DB_URL}
